import sys

from pathlib import Path

WIDTH = 350
HEIGHT = 600
WINDOW_SIZE = (WIDTH, HEIGHT)
FPS = 60

BALL_SPEED = 10
PADDLE_SPEED = 8
SPACESHIP_SPAWN_TIMER = 5000
SPACESHIP_SHOOT_TIMER = 2350
LASER_SPEED = 7

MAIN_FOLDER = Path(sys.argv[0]).parent
IMAGE_FOLDER = MAIN_FOLDER / "assets" / "images"
LEVELS_FOLDER = MAIN_FOLDER / "levels"

PADDLE_IMAGE = "Paddle.png"
BALL_IMAGE = "Ball.png"
SPACESHIP_IMAGE = "Spaceship.png"
LASER_IMAGE = "Laser.png"

BRICK_IMAGE = "Brick"
BRICK_IMAGE_EXT = "png"
NO_OF_BRICK_IMAGES = 3
